export enum SocketEvent {
  banUser = "banuser",
  chatMessage = "chatmessage",
  cheer = "cheer",
  close = "close",
  deleteChatMessage = "deletechatmessage",
  dropEmotes = "dropemotes",
  dropUser = "dropuser",
  error = "error",
  first = "first",
  follow = "follow",
  hypeTrainBegin = "hypetrainbegin",
  hypeTrainEnd = "hypetrainend",
  hypeTrainProgress = "hypetrainprogress",
  imageDrop = "imagedrop",
  open = "open",
  outgoingraid = "outgoingraid",
  raid = "raid",
  raw = "raw",
  shoutOut = "shoutout",
  sub = "sub",
  timeoutUser = "timeoutuser",
  yeetUser = "yeetuser",
}
